-- ===================================================================
-- Hyprland config - Cooper's T480s (Official v0.55 Production Architecture)
-- ===================================================================

hl.config({
    autogenerated = false
})

-- --- MONITORS ---
-- Crisp 1.25 scaling to completely eliminate the coordinate truncation borders
hl.monitor({
    output = "eDP-1",
    mode = "2560x1440@60",
    position = "0x0",
    scale = 1.25
})

-- Pin external monitor above laptop screen
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60",
    position = "0x-1080",
    scale = 1.0
})

-- --- WORKSPACE RULES ---
-- Pin workspaces 1-2 to external monitor, 3-9 to laptop screen
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "3", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "4", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "5", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "6", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "7", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "8", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "9", monitor = "eDP-1" })


-- --- ENVIRONMENT VARIABLES ---
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GSETTINGS_SCHEMA_DIR", "/usr/share/glib-2.0/schemas")

-- --- AUTOSTART ---
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/hyprpolkitagent")
    hl.exec_cmd("mako")
    hl.exec_cmd("waybar")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("sh -c 'sleep 1 && /home/cooper/.local/bin/apply-wallpaper.sh'")
    hl.exec_cmd("sh -c 'sleep 2 && ollama serve'")
end)

-- --- INPUT CONFIGURATION ---
hl.config({
    input = {
        kb_layout = "us",
        repeat_rate = 50,
        repeat_delay = 200,
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.2,
            tap_to_click = true,
            disable_while_typing = true,
            clickfinger_behavior = true
        }
    }
})

-- --- THEME & OPACITY STATE RESOLUTION ---
local theme_file = os.getenv("HOME") .. "/.local/share/theme-mode"
local tf = io.open(theme_file, "r")
local theme_mode = tf and tf:read("*all"):gsub("%s+", "") or "dark"
if tf then tf:close() end

local opacity_file = os.getenv("HOME") .. "/.local/share/opacity-mode"
local of = io.open(opacity_file, "r")
local opacity_mode = of and of:read("*all"):gsub("%s+", "") or "normal"
if of then of:close() end

local active_border = "rgba(5a9fd4ff)"
local inactive_border = "rgba(2d3550a8)"
if theme_mode == "light" then
    active_border = "rgba(1a8cc4ff)"
    inactive_border = "rgba(b0c0d8a8)"
end

local inactive_1_2 = "0.2"
local inactive_3_9 = "0.6"
local inactive_default = 0.4

if opacity_mode == "100" then
    inactive_1_2 = "1.0"
    inactive_3_9 = "1.0"
    inactive_default = 1.0
end

-- --- GENERAL APPEARANCE & STYLING ---
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 2,
        ["col.active_border"] = active_border,
        ["col.inactive_border"] = inactive_border,
        layout = "dwindle"
    },
    decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = inactive_default,
        blur = {
            enabled = false
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(26, 26, 26, 0.93)"
        }
    },
    animations = {
        enabled = true
    },
    windowrulev2 = {
        "float, class:^(fastfetch-popup)$",
        "size 700 500, class:^(fastfetch-popup)$",
        "center, class:^(fastfetch-popup)$",
        "opacity 1.0 override 1.0 override, class:^(code-oss)$",
        
        -- Inactive opacity rules for external monitor (Workspaces 1-2)
        "opacity 1.0 " .. inactive_1_2 .. ", workspace:1",
        "opacity 1.0 " .. inactive_1_2 .. ", workspace:2",

        -- Inactive opacity rules for laptop monitor (Workspaces 3-9)
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:3",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:4",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:5",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:6",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:7",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:8",
        "opacity 1.0 " .. inactive_3_9 .. ", workspace:9"
    }
})

-- ===================================================================
-- PRODUCTION KEYBINDINGS MATRIX
-- ===================================================================
local mainMod = "SUPER"
local mainModShift = "SUPER + SHIFT"

-- Apps & Base Window Control Actions
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("rofi -show drun -show-icons"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nemo"))

-- Windows Operations
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainModShift .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))

-- Focus Navigation Controls (Vim Keys)
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "d" }))

-- Move Window Actions (Shift + Vim Keys)
hl.bind(mainModShift .. " + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainModShift .. " + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainModShift .. " + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainModShift .. " + J", hl.dsp.window.move({ direction = "d" }))

-- Discrete Virtual Workspace Pipelines (1-9 Loop)
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = tostring(i) }))
    hl.bind(mainModShift .. " + " .. i, hl.dsp.window.move({ workspace = tostring(i) }))
end

-- Hardware Subsystem Volume Keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- Display Backlight Brightness Controllers
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })

-- Global Media Stream Keys
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Keyboard Backlight (Fn+F11 / Fn+F12)
hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("brightnessctl --device='tpacpi::kbd_backlight' set 1+"), { locked = true })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl --device='tpacpi::kbd_backlight' set 1-"), { locked = true })

-- Lock screen (Super+Shift+Escape = manual lock; hypridle auto-locks at 5 min)
hl.bind(mainModShift .. " + Escape", hl.dsp.exec_cmd("hyprlock"))

-- Screenshots
-- Print       → full screen, saved directly
-- Super+Shift+Print → region select (grim + slurp)
-- Super+Shift+S     → region select (standard shortcut)
hl.bind("Print", hl.dsp.exec_cmd("grim ~/media/images/screenshots/$(date +%Y%m%d-%H%M%S).png"))
hl.bind(mainModShift .. " + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/media/images/screenshots/$(date +%Y%m%d-%H%M%S).png"))
hl.bind(mainModShift .. " + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/media/images/screenshots/$(date +%Y%m%d-%H%M%S).png"))
hl.bind("Alt_R + Print", hl.dsp.exec_cmd("moondream-ask"))

-- Global theme toggle (light/dark)
-- We bind both Super+F5 and Super+XF86MonBrightnessDown to work regardless of Fn-Lock status
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("/home/cooper/.local/bin/theme-toggle"))
hl.bind(mainMod .. " + XF86MonBrightnessDown", hl.dsp.exec_cmd("/home/cooper/.local/bin/theme-toggle"))


-- Wallpaper controls
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("wallpaper-random"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("wallpaper-back"))
